#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the Unicode category tables DeepSeek-V4's pre-tokenizer regex needs.

WHICH CLASSES, AND WHY
    tokenizer.json's third Split pattern is

        [!"#$%&'()*+,\\-./:;<=>?@\\[\\\\\\]^_`{|}~][A-Za-z]+
      | [^\\r\\n\\p{L}\\p{P}\\p{S}]?[\\p{L}\\p{M}]+
      |  ?[\\p{P}\\p{S}]+[\\r\\n]*
      | \\s*[\\r\\n]+
      | \\s+(?!\\S)
      | \\s+

    so it needs L, M, P and S. The first Split needs N. That is all five.

WHY NOT REUSE kimi-k3-in-c's TABLES
    K3 vendors uni_L, uni_N and uni_S, which would cover three of the five. But
    it has no P table at all, and its uni_X is Lm + Lo + M fused together, so M
    cannot be recovered from it. Generating three classes here and borrowing two
    from K3 would put TWO Unicode versions in one file, and a codepoint that
    moved category between them would land in both classes or neither. So all
    five are generated together, from one unicodedata, and the version is
    recorded in the header.

    That version matters: the reference tokenizer is Rust `regex` with its own
    embedded tables. Where the two disagree, the C tokenizer disagrees with the
    checkpoint. The parity gate against the shipped encoding tests is what
    detects that; this header records what was used so the answer is findable.

Usage:  python3 tools/gen_unicode.py > third_party/dsv4_unicode.h
"""
import sys
import unicodedata

CLASSES = {
    "L": ("Lu", "Ll", "Lt", "Lm", "Lo"),
    "N": ("Nd", "Nl", "No"),
    "P": ("Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po"),
    "S": ("Sm", "Sc", "Sk", "So"),
    "M": ("Mn", "Mc", "Me"),
}

MAX_CP = 0x110000


def ranges_for(cats):
    want = set(cats)
    out, start, prev = [], None, None
    for cp in range(MAX_CP):
        # Surrogates have no assigned category and never appear in valid UTF-8.
        if 0xD800 <= cp <= 0xDFFF:
            inside = False
        else:
            inside = unicodedata.category(chr(cp)) in want
        if inside:
            if start is None:
                start = cp
            prev = cp
        elif start is not None:
            out.append((start, prev))
            start = None
    if start is not None:
        out.append((start, prev))
    return out


def emit(name, rs, f):
    f.write(f"static const uint32_t uni_{name}[][2] = {{\n")
    for i in range(0, len(rs), 6):
        chunk = rs[i:i + 6]
        f.write("    " + ",".join(f"{{0x{a:X},0x{b:X}}}" for a, b in chunk) + ",\n")
    f.write("};\n")
    f.write(f"static const int uni_{name}_n = "
            f"(int)(sizeof uni_{name} / sizeof uni_{name}[0]);\n\n")


def main():
    f = sys.stdout
    f.write("/* GENERATED by tools/gen_unicode.py, do not edit by hand.\n")
    f.write(f" * Unicode {unicodedata.unidata_version}, "
            f"Python {sys.version.split()[0]}.\n")
    f.write(" *\n")
    f.write(" * Classes L, N, P, S, M for the DeepSeek-V4 pre-tokenizer regex.\n")
    f.write(" * All five come from ONE unicodedata so a codepoint cannot be in\n")
    f.write(" * two classes at once through version skew -- see the generator.\n")
    f.write(" */\n")
    f.write("#ifndef DSV4_UNICODE_H\n#define DSV4_UNICODE_H\n#include <stdint.h>\n\n")

    total = 0
    for name in ("L", "N", "P", "S", "M"):
        rs = ranges_for(CLASSES[name])
        total += len(rs)
        emit(name, rs, f)
        print(f"  uni_{name}: {len(rs)} ranges", file=sys.stderr)

    f.write("""/* Binary search over sorted, non-overlapping ranges. */
static int uni_in(const uint32_t t[][2], int n, uint32_t cp)
{
    int lo = 0, hi = n - 1;
    while (lo <= hi) {
        const int mid = (lo + hi) / 2;
        if (cp < t[mid][0])      hi = mid - 1;
        else if (cp > t[mid][1]) lo = mid + 1;
        else                     return 1;
    }
    return 0;
}

static inline int dsv4_is_L(uint32_t c) { return uni_in(uni_L, uni_L_n, c); }
static inline int dsv4_is_N(uint32_t c) { return uni_in(uni_N, uni_N_n, c); }
static inline int dsv4_is_P(uint32_t c) { return uni_in(uni_P, uni_P_n, c); }
static inline int dsv4_is_S(uint32_t c) { return uni_in(uni_S, uni_S_n, c); }
static inline int dsv4_is_M(uint32_t c) { return uni_in(uni_M, uni_M_n, c); }

#endif /* DSV4_UNICODE_H */
""")
    print(f"  total {total} ranges", file=sys.stderr)


if __name__ == "__main__":
    main()
